### PR TITLE
SecureSubmit JS to GlobalPayment JS migrations (Security compliance update)

### PR DESCRIPTION
**Pull request by mayur-vachchewar**

### CODE REVIEW

**Comment by mayur-vachchewar** [comment]
@MSmedal Could you please review the PR.

**Comment by MSmedal** [comment]
Looking good! Here are two things to cleanup:

There seem to be a lot of warnings in my testing:
image

... can you address those and also any other items a linter will find for PHP 8 environments?

The input fields and submit button don't quite duplicate the current look and feel of the plugin. Can you modify the styling to match?

**Comment by mayur-vachchewar** [comment]
> Looking good! Here are two things to cleanup:
> 
> There seem to be a lot of warnings in my testing: image
> 
> ... can you address those and also any other items a linter will find for PHP 8 environments?
> 
> The input fields and submit button don't quite duplicate the current look and feel of the plugin. Can you modify the styling to match?

@MSmedal I have fixed the warning issues, and the UI. could you please review it once and let me know if anything

**Comment by MSmedal** [comment]
@mayur-vachchewar there still seem to be issues in terms of appearance and display. Here what it currently looks like in large viewports:
image

...and here is the way your PR renders:
image

The spacing between some input fields, the images we're loading, and especially the submit button all have problems. Please try to copy the look and feel of the current plugin.

**Review by MSmedal — CHANGES_REQUESTED** [review]
Everything looks great except for the Submit button still seems to be missing some styling:
image

**Review by securesubmit-buildmaster — CHANGES_REQUESTED** [review]
This change has no effect because this public method isn't actually being used. Double-check to see where 'style.css' is actually being loaded, it isn't here.

**Comment by mayur-vachchewar** [comment]
> This change has no effect because this public method isn't actually being used. Double-check to see where 'style.css' is actually being loaded, it isn't here.

@securesubmit-buildmaster @MSmedal 
This will only get reflect after changing the version example, as I am unable to reproduce the issue, so could you try with updating version mention --> define('GF_SECURESUBMIT_VERSION', '1.4.8');

image

In below images, the version of style.css is been refer to the plugin version.  
image


Here is the file for reference : 
[define('GF_SECURESUBMIT_VERSION', '1.4.8');](https://github.com/hps/heartland-gravity-forms-addon/blob/master/gravityforms-securesubmit.php#L11)

**Review by MSmedal — APPROVED** [review]

**Pull request merged**
